/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AirportsIndexRouteImport } from './routes/airports/index'
import { Route as AirportsCodeRouteImport } from './routes/airports/$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportsIndexRoute = AirportsIndexRouteImport.update({
  id: '/airports/',
  path: '/airports/',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportsCodeRoute = AirportsCodeRouteImport.update({
  id: '/airports/$code',
  path: '/airports/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/airports/$code': typeof AirportsCodeRoute
  '/airports': typeof AirportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/airports/$code': typeof AirportsCodeRoute
  '/airports': typeof AirportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/airports/$code': typeof AirportsCodeRoute
  '/airports/': typeof AirportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/airports/$code' | '/airports'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/airports/$code' | '/airports'
  id: '__root__' | '/' | '/airports/$code' | '/airports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AirportsCodeRoute: typeof AirportsCodeRoute
  AirportsIndexRoute: typeof AirportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airports/': {
      id: '/airports/'
      path: '/airports'
      fullPath: '/airports'
      preLoaderRoute: typeof AirportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airports/$code': {
      id: '/airports/$code'
      path: '/airports/$code'
      fullPath: '/airports/$code'
      preLoaderRoute: typeof AirportsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AirportsCodeRoute: AirportsCodeRoute,
  AirportsIndexRoute: AirportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
